name: steinkamp_us_prod
services:
  web:
    build:
      context: .
      target: prod
    ports:
      - '3125:3125'
    restart: unless-stopped
    volumes:
      - ./public/zip:/app/public/zip
volumes:
  app_node_modules:
