version: '3'
name: steinkamp_us_dev
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
volumes:
  app_node_modules:
